version: '3.8'
services:
  app:
    build: .
    image: warrickb/node-web-app
    ports:
      - '3040:3040'
    environment:
      - PORT=3040
    container_name: my-app-0
    networks:
      - my-net

  app1:
    build: .
    image: warrickb/node-web-app
    ports:
      - '3041:3040'
    environment:
      - PORT=3040
    container_name: my-app1
    networks:
      - my-net

networks:
  my-net:
    driver: bridge