apiVersion: v1
kind: Pod # Pod is one level abstraction above container to have more control (container to hold containers)
metadata: #infomation realted to pod
  name: mypod
  labels:
    category: frontend0
spec: #specifications is how to go about creating pod
  containers:
    # Image to be used
    - image: warrickb/nodewebapp:1.1.1
      name: nodewebapp
      ports:
        - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
