apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
spec:
  selector:
    category: frontend
  clusterIP: 10.99.131.100 #external IP
  externalTrafficPolicy: Cluster
  ports:
    - name: myport
      port: 8095 #external port
      protocol: TCP
      targetPort: 3040 #internal port
  type: LoadBalancer
