version: '3.8'
services:
  app:
    build: .
    image: warrickb/nodewebapp
    ports:
      - '3043:3040'
    environment:
      - PORT=3043
    container_name: my-app-4
    networks:
      - my-net

  app1:
    build: .
    image: warrickb/nodewebapp
    ports:
      - '3044:3040'
    environment:
      - PORT=3044
    container_name: my-app-3
    networks:
      - my-net


networks:
  my-net:
    driver: bridge